version: '3'

services:
  backend:
    build: ./src/blog-demo-backend
    command: make run-inside-container
    environment:
      MAIN_CONFIG_PATH: /var/www/src/config/main.container.json
      VENV_DIR: /opt/hl
    deploy:
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 100m
    ports:
      - "8888:8888"
    volumes:
      - ./:/var/www
      - /tmp/blog_demo:/tmp/blog_demo
    links:
      - db
      - permission-service

  alertmanager:
    build:
      context: ./src/high-load/alerting/
      dockerfile: alertmanager.Dockerfile
    command:
      - '--config.file=/etc/prometheus/alertmanager.yaml'
    ports:
      - "9093:9093"
    depends_on:
      - backend

  prometheus:
    build:
      context: ./src/high-load/monitoring/
      dockerfile: prometheus.Dockerfile
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager
