version: '3'

services:
  backend:
    build: ./src/blog-demo-backend
    command: make run-inside-container
    environment:
      MAIN_CONFIG_PATH: /var/www/src/config/main.container.json
      VENV_DIR: /opt/hl
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100m
    ports:
      - "8888:8888"
    volumes:
      - ./:/var/www
      - /tmp/blog_demo:/tmp/blog_demo
    links:
      - db
      - permission-service
