version: '3'

services:
  backend:
    build: ./src/blog-demo-backend
    command: make run-inside-container
    environment:
      MAIN_CONFIG_PATH: /var/www/src/config/main.container.json
      VENV_DIR: /opt/hl
    deploy:
      resources:
        limits:
          memory: 750M
        reservations:
          memory: 100m
    expose:
      - "8888"
    volumes:
      - ./:/var/www
      - /tmp/blog_demo:/tmp/blog_demo
    links:
      - db
      - message-broker
      - permission-service

  nginx:
    image: nginx:latest
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"

  alertmanager:
    build:
      context: ./src/high-load/alerting/
      dockerfile: alertmanager.Dockerfile
    command:
      - "--config.file=/etc/prometheus/alertmanager.yaml"
    ports:
      - "9093:9093"
    depends_on:
      - backend

  prometheus:
    build:
      context: ./src/high-load/monitoring/
      dockerfile: prometheus.Dockerfile
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager
