route:
  receiver: "request-latency-receiver"
  # тут имеет смысл сделать интервалы небольшими, чтобы получать больше инфы в приложении
  repeat_interval: 5s
  group_interval: 5s

receivers:
  - name: "request-latency-receiver"
    webhook_configs:
      - url: "http://backend:8888/alert"
        http_config:
          basic_auth:
            username: "blog-demo-internal-user"
            password: "bd_password"
